"""mira-diagnose-verify skill — diagnose stage.

Thin wrapper around ``mira.pipeline.diagnose_only``.  Runs stages 1-3
(diagnosis + System B verification) and emits a diagnosis JSON to stdout.

Intentional omissions (pre-coaching stage):
  - ``report``   — generated by ``mira.report.generate_report``; not called here.
  - ``coaching`` — populated by ``mira.pipeline.coach_from_overlay``; not called.

JSON contract (mirrors ``build_json_output`` in ``mira/__main__.py``, minus the
report/coaching keys):
  schema_version, input, route_vtype, psr{P,S,R}, patterns[], overlay_status,
  evidence_summary.

Usage:
    python diagnose.py "I failed because I'm not smart enough."
    python diagnose.py --lang ko "시험에 떨어진 것은 내가 머리가 나빠서다."
    echo "text" | python diagnose.py --stdin
    python diagnose.py path/to/file.txt
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import TYPE_CHECKING

# BUG-1: when run directly (python skills/.../scripts/diagnose.py), sys.path[0]
# is the script dir, not the project root, so `import mira` fails — this project
# is not installed into site-packages. Bootstrap the project root onto sys.path.
_PROJECT_ROOT = Path(__file__).resolve().parents[3]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

if TYPE_CHECKING:
    from mira.pipeline import DiagnoseResult


def _build_diagnose_json(diag: DiagnoseResult, learner_input: str = "") -> dict:
    """Serialize a DiagnoseResult into the diagnosis-subset JSON contract.

    Reuses the same field structure as ``build_json_output`` in
    ``mira/__main__.py`` but deliberately omits ``report`` and ``coaching``
    (this is the pre-coaching stage).

    Retains: schema_version, input, route_vtype, psr, patterns,
             overlay_status, evidence_summary.
    Omits:   report (not generated), coaching (not generated), lane1_pass
             (lane1 critic runs in coach_from_overlay, not diagnose_only).
    """
    from mira.report import SCHEMA_VERSION

    overlay = diag.overlay
    return {
        "schema_version": SCHEMA_VERSION,
        "input": learner_input,
        "route_vtype": overlay.route_vtype,
        "psr": {
            "P": overlay.psr.P_appraisal,
            "S": overlay.psr.S_strategy,
            "R": overlay.psr.R_projection,
        },
        "patterns": [
            {
                "pattern_id": c.pattern_id,
                "lane2_status": c.lane2_status,
                "evidence_trace": c.evidence_trace,
                **({"lane2_result": c.lane2_result} if c.lane2_result else {}),
            }
            for c in overlay.pattern_candidates
        ],
        "overlay_status": overlay.overlay_status,
        "evidence_summary": overlay.evidence_summary,
    }
    # Intentionally absent keys:
    #   "report"   — requires generate_report (stage 4 / coach_from_overlay)
    #   "coaching" — requires coach_from_overlay (stage 4)
    #   "lane1_pass" — set by run_reduced_critic inside coach_from_overlay


def _load_dotenv() -> None:
    env_path = Path.cwd() / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            key, value = key.strip(), value.strip()
            if key and key not in os.environ:
                os.environ[key] = value


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="diagnose",
        description=(
            "mira-diagnose-verify — run stages 1-3 (diagnosis + System B "
            "verification) and emit a diagnosis JSON to stdout. "
            "Coaching and report are intentionally absent (pre-coaching stage)."
        ),
    )
    parser.add_argument(
        "input",
        nargs="?",
        help="Learner text (direct input, file path, or omit to use --stdin)",
    )
    parser.add_argument(
        "--lang",
        default="en",
        choices=["ko", "en"],
        help="Output language (default: en)",
    )
    parser.add_argument(
        "--stdin",
        action="store_true",
        help="Read learner text from stdin instead of positional argument",
    )

    args = parser.parse_args()

    _load_dotenv()

    # Resolve input text: --stdin, positional file path, or positional literal
    if args.stdin:
        claim = sys.stdin.read().strip()
    elif args.input is not None:
        input_path = Path(args.input)
        try:
            is_file = input_path.exists() and input_path.is_file()
        except OSError:
            is_file = False
        if is_file:
            claim = input_path.read_text(encoding="utf-8").strip()
        else:
            claim = args.input
    else:
        print("Error: provide input text or use --stdin.", file=sys.stderr)
        sys.exit(1)

    if not claim:
        print("Error: input text is empty.", file=sys.stderr)
        sys.exit(1)

    from mira.pipeline import diagnose_only

    diag = diagnose_only(claim, lang=args.lang)
    output = _build_diagnose_json(diag, learner_input=claim)
    print(json.dumps(output, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
